spring:
  datasource:
    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/biot_admin
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

    datasource-app:
      jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/vendas_analytics
      username: postgres
      password: 1y5h8j
      initialization-mode: always
      initialize: true
      continue-on-error: true
      platform: postgresql
      driver-class-name: org.postgresql.Driver

  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true