spring:
  datasource:
    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/biot_admin
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  datasource-app:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/nutricao_esportiva
    username: postgres
    password: 1y5h8j
    hikari:
      maximumPoolSize: 2

  main:
    allow-bean-definition-overriding: true

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

app-config:
  oauth-clients:
    biot-admin:
      client: biot_admin-client
      secret: biot_admin-secret
    guia-de-projeto-api:
      client: guia-de-projeto-api-client
      secret: guia-de-projeto-api-secret

  services:
    guia-de-projeto-api:
      url: http://localhost:8090
    biot-admin:
      url: http://localhost:8080

security:
  oauth2:
    resource:
      filter-order: 3